credentials:
  usernames:
    yingyi:
      email: yingyidu@gmail.com
      name: Ying Yi Du
      password: aff5259e # To be replaced with hashed password
    guest:
      name: Gast
      password: 61e1256b # To be replaced with hashed password
cookie:
  expiry_days: 30  # number of days until password is asked again
  key: BzBT=qOywNHH%:&EJ=C5o|h7$e.KM& # Must be string, use https://randomkeygen.com/
  name: streamlitcookie
  
hashed_passwords = stauth.Hasher(['abc', 'def']).generate()
